BUTTON_LOGIN_LOCATOR = "//button[contains(@class, 'btn-primary') and contains(text(), 'Customer Login')]"
SELECT_LOGIN_LOCATOR = "#userSelect"
SELECT_LOGIN_ALL_OPTIONS_LOCATOR = "//option[@ng-repeat='cust in Customers']"
SELECT_LOGIN_OPTION_3_LOCATOR = "//option[@value='3']"
BUTTON_LOGIN_WITH_OPTION_LOCATOR = "//button[@class='btn btn-default']"
